import { useEffect, useState } from "react";
import yaml from "js-yaml";
import {
  githubApi, GithubTarget, instancesApi, NetboxInstance,
  customFieldsApi, CustomFieldsTemplateFile, InstanceCustomFieldsDiffResult,
} from "../api/client";
import ComponentGrid, { FieldDef } from "../components/ComponentGrid";

const CF_TYPES = [
  "text", "longtext", "integer", "decimal", "boolean", "date", "datetime",
  "url", "json", "select", "multiselect", "object", "multiobject",
];
const FILTER_LOGIC = ["disabled", "loose", "exact"];
const UI_VISIBLE = ["always", "if-set", "hidden"];
const UI_EDITABLE = ["yes", "no", "hidden"];

const CUSTOM_FIELD_FIELDS: FieldDef[] = [
  { key: "name", label: "Name", width: "12%" },
  { key: "label", label: "Label", width: "12%" },
  { key: "type", label: "Type", type: "select", options: CF_TYPES, width: "10%" },
  { key: "content_types", label: "Content types (csv)", type: "csv", width: "16%" },
  { key: "choice_set", label: "Choice set" },
  { key: "required", label: "Req'd", type: "checkbox", width: "6%" },
  { key: "group_name", label: "Group" },
  { key: "filter_logic", label: "Filter", type: "select", options: FILTER_LOGIC, width: "8%" },
  { key: "ui_visible", label: "UI visible", type: "select", options: UI_VISIBLE, width: "9%" },
  { key: "ui_editable", label: "UI editable", type: "select", options: UI_EDITABLE, width: "9%" },
];

const CHOICE_SET_FIELDS: FieldDef[] = [
  { key: "name", label: "Name", width: "20%" },
  { key: "description", label: "Description", width: "25%" },
  { key: "extra_choices", label: "Choices (value=Label per line)", type: "pairs", width: "45%" },
  { key: "order_alphabetically", label: "Sort A-Z", type: "checkbox", width: "10%" },
];

function generateCommitMessage(payload: any): string {
  return `Update custom-fields template (${(payload.custom_fields ?? []).length} fields, ${(payload.custom_field_choice_sets ?? []).length} choice sets)`;
}

function generatePrBody(payload: any): string {
  return `Updates the custom-fields template: ${(payload.custom_fields ?? []).length} custom field(s), `
    + `${(payload.custom_field_choice_sets ?? []).length} choice set(s).\n\n_Generated by NetBox Manager._`;
}

export default function CustomFieldsPage() {
  const [targets, setTargets] = useState<GithubTarget[]>([]);
  const [selectedTarget, setSelectedTarget] = useState("");
  const [file, setFile] = useState<CustomFieldsTemplateFile | null>(null);
  const [activeTab, setActiveTab] = useState<"fields" | "choice-sets" | "publish">("fields");
  const [dirty, setDirty] = useState(false);
  const [saving, setSaving] = useState(false);
  const [commitMessage, setCommitMessage] = useState("");
  const [commitTouched, setCommitTouched] = useState(false);
  const [prBody, setPrBody] = useState("");
  const [prBodyTouched, setPrBodyTouched] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [lastResult, setLastResult] = useState<{ pr_number: number; pr_url: string } | null>(null);

  const [instances, setInstances] = useState<NetboxInstance[]>([]);
  const [selectedInstances, setSelectedInstances] = useState<string[]>([]);
  const [overwrite, setOverwrite] = useState(false);
  const [pushResults, setPushResults] = useState<{ target: string; status: string; detail?: string }[]>([]);
  const [diffResults, setDiffResults] = useState<InstanceCustomFieldsDiffResult[] | null>(null);
  const [diffing, setDiffing] = useState(false);
  const [importInstance, setImportInstance] = useState("");
  const [importing, setImporting] = useState(false);

  useEffect(() => {
    githubApi.list().then((t) => { setTargets(t); if (t.length > 0) setSelectedTarget(t[0].id); });
    instancesApi.list().then(setInstances);
  }, []);

  const loadFile = () => {
    if (!selectedTarget) return;
    customFieldsApi.get(selectedTarget).then((f) => { setFile(f); setDirty(false); setLastResult(null); });
  };
  useEffect(() => { loadFile(); }, [selectedTarget]);

  useEffect(() => {
    if (!file) return;
    if (!commitTouched) setCommitMessage(generateCommitMessage(file.payload));
    if (!prBodyTouched) setPrBody(generatePrBody(file.payload));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [file?.payload]);

  if (targets.length === 0) {
    return (
      <div>
        <h1>Custom Fields</h1>
        <p className="page-subtitle">Add a GitHub target first — the custom-fields template lives in that repo, in its own folder.</p>
      </div>
    );
  }
  if (!file) return <p>Loading…</p>;

  const updateFields = (rows: Record<string, any>[]) => {
    setFile({ ...file, payload: { ...file.payload, custom_fields: rows } });
    setDirty(true);
  };
  const updateChoiceSets = (rows: Record<string, any>[]) => {
    setFile({ ...file, payload: { ...file.payload, custom_field_choice_sets: rows } });
    setDirty(true);
  };

  const handleSave = async () => {
    setSaving(true);
    setSaveError(null);
    try {
      const result = await customFieldsApi.save(selectedTarget, {
        payload: file.payload, sha: file.sha ?? undefined, commit_message: commitMessage, pr_body: prBody,
      });
      setLastResult(result);
      setDirty(false);
      loadFile();
    } catch (err: any) {
      setSaveError(err.message ?? "Save failed.");
    } finally {
      setSaving(false);
    }
  };

  const handleImport = async () => {
    if (!importInstance) return;
    setImporting(true);
    try {
      const result = await customFieldsApi.importFromInstance(selectedTarget, importInstance, file.sha ?? undefined);
      setLastResult(result);
      loadFile();
    } finally {
      setImporting(false);
    }
  };

  const handlePush = async () => {
    const results = await customFieldsApi.push(selectedTarget, selectedInstances, [], overwrite);
    setPushResults(results);
  };

  const handleDiff = async () => {
    if (selectedInstances.length === 0) return;
    setDiffing(true);
    try {
      const results = await customFieldsApi.diff(selectedTarget, selectedInstances, []);
      setDiffResults(results);
    } finally {
      setDiffing(false);
    }
  };

  const allTags = Array.from(new Set(instances.flatMap((i) => i.tags))).sort();
  const selectByTag = (tag: string) => {
    const matching = instances.filter((i) => i.tags.includes(tag)).map((i) => i.id);
    setSelectedInstances((prev) => Array.from(new Set([...prev, ...matching])));
  };

  const yamlPreview = yaml.dump(file.payload, { sortKeys: false });

  return (
    <div>
      <h1>Custom Fields Template</h1>
      <div className="toolbar">
        <select value={selectedTarget} onChange={(e) => setSelectedTarget(e.target.value)} style={{ maxWidth: 280 }}>
          {targets.map((t) => <option key={t.id} value={t.id}>{t.name} ({t.repo}@{t.branch})</option>)}
        </select>
      </div>
      <p className="page-subtitle mono">
        {file.exists
          ? file.path
          : <span className="pill" style={{ color: "var(--warning)" }}>template doesn't exist in this repo yet — save to create it</span>}
      </p>
      {file.open_pr && (
        <div className="card" style={{ borderColor: "var(--warning)" }}>
          <p style={{ fontSize: 13, margin: 0 }}>
            This template already has an open pull request —{" "}
            <a href={file.open_pr.url} target="_blank" rel="noreferrer" style={{ color: "var(--accent)" }}>PR #{file.open_pr.number}</a>.
            Saving again adds another commit to that same PR.
          </p>
        </div>
      )}

      <div className="editor-layout">
        <div>
          <div className="tabs">
            <button className={activeTab === "fields" ? "active" : ""} onClick={() => setActiveTab("fields")}>
              Custom Fields ({(file.payload.custom_fields ?? []).length})
            </button>
            <button className={activeTab === "choice-sets" ? "active" : ""} onClick={() => setActiveTab("choice-sets")}>
              Choice Sets ({(file.payload.custom_field_choice_sets ?? []).length})
            </button>
            <button className={activeTab === "publish" ? "active" : ""} onClick={() => setActiveTab("publish")}>
              Import / Push / Drift
            </button>
          </div>

          {activeTab === "fields" && (
            <div className="card">
              <ComponentGrid rows={file.payload.custom_fields ?? []} fields={CUSTOM_FIELD_FIELDS} onChange={updateFields} />
            </div>
          )}
          {activeTab === "choice-sets" && (
            <div className="card">
              <ComponentGrid rows={file.payload.custom_field_choice_sets ?? []} fields={CHOICE_SET_FIELDS} onChange={updateChoiceSets} />
            </div>
          )}

          {activeTab === "publish" && (
            <div>
              <div className="card">
                <h2>Import from a NetBox instance</h2>
                <p style={{ color: "var(--muted)", fontSize: 13, marginTop: -6 }}>
                  Replaces the entire template with whatever custom fields/choice sets currently exist on the
                  chosen instance, then opens it as a PR — nothing is written until you review and it merges.
                </p>
                <div className="form-row">
                  <select value={importInstance} onChange={(e) => setImportInstance(e.target.value)}>
                    <option value="">— select instance —</option>
                    {instances.map((i) => <option key={i.id} value={i.id}>{i.name}</option>)}
                  </select>
                </div>
                <button className="primary" disabled={!importInstance || importing} onClick={handleImport}>
                  {importing ? "Importing…" : "Import & open PR"}
                </button>
              </div>

              <div className="card">
                <h2>Push to NetBox instance(s)</h2>
                <p style={{ color: "var(--muted)", fontSize: 13, marginTop: -6 }}>
                  Pushes the template's current merged (base-branch) state. Missing fields/choice sets are created;
                  existing ones are only updated if "Overwrite" is checked.
                </p>
                {allTags.length > 0 && (
                  <div style={{ marginBottom: 10 }}>
                    <span style={{ fontSize: 12, color: "var(--muted)", marginRight: 8 }}>Select by tag:</span>
                    {allTags.map((tag) => (
                      <button key={tag} onClick={() => selectByTag(tag)} style={{ marginRight: 6, padding: "3px 10px", fontSize: 12 }}>
                        {tag} ({instances.filter((i) => i.tags.includes(tag)).length})
                      </button>
                    ))}
                    <button onClick={() => setSelectedInstances(instances.map((i) => i.id))} style={{ padding: "3px 10px", fontSize: 12 }}>all</button>
                    <button onClick={() => setSelectedInstances([])} style={{ padding: "3px 10px", fontSize: 12 }}>clear</button>
                  </div>
                )}
                {instances.map((inst) => (
                  <label key={inst.id} style={{ display: "block", marginBottom: 6 }}>
                    <input
                      type="checkbox" style={{ width: "auto", marginRight: 6 }}
                      checked={selectedInstances.includes(inst.id)}
                      onChange={(e) => setSelectedInstances((prev) =>
                        e.target.checked ? [...prev, inst.id] : prev.filter((x) => x !== inst.id))}
                    />
                    {inst.name}
                    {inst.requires_approved_pr && <span className="pill" style={{ marginLeft: 6 }}>🔒 needs approved PR</span>}
                  </label>
                ))}
                <label style={{ display: "block", margin: "10px 0" }}>
                  <input type="checkbox" style={{ width: "auto", marginRight: 6 }} checked={overwrite} onChange={(e) => setOverwrite(e.target.checked)} />
                  Overwrite existing fields/choice sets
                </label>
                <div className="toolbar">
                  <button disabled={selectedInstances.length === 0 || diffing} onClick={handleDiff}>
                    {diffing ? "Checking…" : "Check drift"}
                  </button>
                  <button className="primary" disabled={selectedInstances.length === 0} onClick={handlePush}>
                    Push to {selectedInstances.length || ""} instance(s)
                  </button>
                </div>

                {diffResults && diffResults.map((r) => (
                  <div key={r.instance_id} className="card" style={{ background: "var(--panel-raised)" }}>
                    <p style={{ fontWeight: 600, marginBottom: 6 }}>{r.instance_name}</p>
                    {r.error ? (
                      <p style={{ color: "var(--danger)", fontSize: 13 }}>Could not check: {r.error}</p>
                    ) : r.diff?.status === "in_sync" ? (
                      <p style={{ color: "var(--success)", fontSize: 13 }}>In sync with template.</p>
                    ) : (
                      <div style={{ fontSize: 13 }}>
                        {(["custom_fields", "custom_field_choice_sets"] as const).map((key) => {
                          const d = r.diff?.[key];
                          if (!d || (!d.missing_on_instance.length && !d.extra_on_instance.length && !d.changed.length)) return null;
                          return (
                            <div key={key} style={{ marginBottom: 4 }}>
                              <span style={{ color: "var(--muted)" }}>{key === "custom_fields" ? "Custom fields" : "Choice sets"}: </span>
                              {d.missing_on_instance.length > 0 && <span style={{ color: "var(--danger)" }}>missing on instance: {d.missing_on_instance.join(", ")} </span>}
                              {d.extra_on_instance.length > 0 && <span style={{ color: "var(--warning)" }}>extra on instance (not in template): {d.extra_on_instance.join(", ")} </span>}
                              {d.changed.length > 0 && <span style={{ color: "var(--warning)" }}>changed: {d.changed.join(", ")}</span>}
                            </div>
                          );
                        })}
                      </div>
                    )}
                  </div>
                ))}
                {pushResults.map((r, i) => (
                  <p key={i} style={{ fontSize: 13 }}>
                    <span className={`status-dot ${r.status === "success" ? "status-ok" : "status-error"}`} />
                    {r.target}: {r.detail}
                  </p>
                ))}
              </div>
            </div>
          )}

          <div className="card" style={{ marginTop: 8 }}>
            <h2>Commit</h2>
            <p style={{ color: "var(--muted)", fontSize: 13, marginTop: -6 }}>
              Direct commits are disabled — saving always opens (or updates) a pull request for review.
            </p>
            <div className="form-row">
              <label>PR title / commit message</label>
              <input value={commitMessage} onChange={(e) => { setCommitMessage(e.target.value); setCommitTouched(true); }} />
            </div>
            <div className="form-row">
              <label>PR description</label>
              <textarea rows={4} className="mono" value={prBody} onChange={(e) => { setPrBody(e.target.value); setPrBodyTouched(true); }} />
            </div>
            <button className="primary" disabled={!dirty || saving} onClick={handleSave}>
              {saving ? "Opening PR…" : dirty ? "Save (open pull request)" : "Saved"}
            </button>
            {saveError && <p style={{ color: "var(--danger)", fontSize: 13 }}>{saveError}</p>}
            {lastResult && !dirty && (
              <p style={{ fontSize: 13 }}>
                <span className="status-dot status-ok" />
                Saved to <a href={lastResult.pr_url} target="_blank" rel="noreferrer" style={{ color: "var(--accent)" }}>PR #{lastResult.pr_number}</a>
              </p>
            )}
          </div>
        </div>

        <div>
          <h2>YAML preview</h2>
          <pre className="yaml-preview mono">{yamlPreview}</pre>
        </div>
      </div>
    </div>
  );
}
