import { useEffect, useRef, useState } from "react";
import * as yaml from "js-yaml";
import {
  githubApi, GithubTarget, instancesApi, NetboxInstance,
  customFieldsApi, CustomFieldsTemplateFile, InstanceCustomFieldsDiffResult, ImportCandidate,
  InstanceScopePreview,
} from "../api/client";
import { CustomFieldsDiffView } from "../components/DiffView";
import CustomFieldForm from "../components/CustomFieldForm";
import ChoiceSetForm from "../components/ChoiceSetForm";

function generateCommitMessage(payload: any): string {
  return `Update custom-fields template (${(payload.custom_fields ?? []).length} fields, ${(payload.custom_field_choice_sets ?? []).length} choice sets)`;
}

function generatePrBody(payload: any): string {
  return `Updates the custom-fields template: ${(payload.custom_fields ?? []).length} custom field(s), `
    + `${(payload.custom_field_choice_sets ?? []).length} choice set(s).\n\n_Generated by NetBox Manager._`;
}

export default function CustomFieldsPage() {
  const [targets, setTargets] = useState<GithubTarget[]>([]);
  const [targetsLoading, setTargetsLoading] = useState(true);
  const [targetsError, setTargetsError] = useState<string | null>(null);
  const [selectedTarget, setSelectedTarget] = useState("");
  const [file, setFile] = useState<CustomFieldsTemplateFile | null>(null);
  const [fileLoading, setFileLoading] = useState(false);
  const [fileError, setFileError] = useState<string | null>(null);
  const fileRequestId = useRef(0);
  const [activeTab, setActiveTab] = useState<"fields" | "choice-sets" | "publish">("fields");
  const [dirty, setDirty] = useState(false);
  const [saving, setSaving] = useState(false);
  const [commitMessage, setCommitMessage] = useState("");
  const [commitTouched, setCommitTouched] = useState(false);
  const [prBody, setPrBody] = useState("");
  const [prBodyTouched, setPrBodyTouched] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [lastResult, setLastResult] = useState<{ pr_number: number; pr_url: string } | null>(null);

  const [instances, setInstances] = useState<NetboxInstance[]>([]);
  const [selectedInstances, setSelectedInstances] = useState<string[]>([]);
  const [overwrite, setOverwrite] = useState(false);
  const [pushResults, setPushResults] = useState<{ target: string; status: string; detail?: string; warnings?: string[] }[]>([]);
  const [pushPreviews, setPushPreviews] = useState<InstanceScopePreview[] | null>(null);
  const [backupEnabled, setBackupEnabled] = useState(true);
  const [scopeConfirmations, setScopeConfirmations] = useState<Record<string, string>>({});
  const [backupOptOutConfirmations, setBackupOptOutConfirmations] = useState<Record<string, string>>({});
  const [previewingPush, setPreviewingPush] = useState(false);
  const [restoreInstance, setRestoreInstance] = useState("");
  const [restoreBackup, setRestoreBackup] = useState<Record<string, any> | null>(null);
  const [restoreResult, setRestoreResult] = useState<any>(null);
  const [diffResults, setDiffResults] = useState<InstanceCustomFieldsDiffResult[] | null>(null);
  const [diffing, setDiffing] = useState(false);
  const [importInstance, setImportInstance] = useState("");
  const [scanning, setScanning] = useState(false);
  const [scanError, setScanError] = useState<string | null>(null);
  const [candidates, setCandidates] = useState<ImportCandidate[] | null>(null);
  const [selectedCandidates, setSelectedCandidates] = useState<Set<string>>(new Set());
  const [importing, setImporting] = useState(false);
  const [importError, setImportError] = useState<string | null>(null);
  const [importResult, setImportResult] = useState<{ pr_number: number; pr_url: string } | null>(null);

  const [fieldFormOpen, setFieldFormOpen] = useState<{ index: number | null } | null>(null);
  const [choiceSetFormOpen, setChoiceSetFormOpen] = useState<{ index: number | null } | null>(null);

  const errorMessage = (error: unknown, fallback: string) =>
    error instanceof Error ? error.message : fallback;

  const loadTargets = async () => {
    setTargetsLoading(true);
    setTargetsError(null);
    try {
      const nextTargets = await githubApi.list();
      setTargets(nextTargets);
      setSelectedTarget((current) =>
        current && nextTargets.some((target) => target.id === current)
          ? current
          : nextTargets[0]?.id ?? ""
      );
    } catch (error) {
      setTargetsError(errorMessage(error, "Could not load GitHub targets."));
    } finally {
      setTargetsLoading(false);
    }
  };

  useEffect(() => {
    void loadTargets();
    instancesApi.list().then(setInstances).catch(() => setInstances([]));
  }, []);

  const loadFile = async () => {
    if (!selectedTarget) return;
    const requestId = ++fileRequestId.current;
    const targetId = selectedTarget;
    setFileLoading(true);
    setFileError(null);
    try {
      const nextFile = await customFieldsApi.get(targetId);
      if (requestId !== fileRequestId.current) return;
      setFile(nextFile);
      setDirty(false);
      setLastResult(null);
    } catch (error) {
      if (requestId !== fileRequestId.current) return;
      setFileError(errorMessage(error, "Could not load the custom-fields template."));
    } finally {
      if (requestId === fileRequestId.current) setFileLoading(false);
    }
  };
  useEffect(() => {
    setFile(null);
    if (selectedTarget) void loadFile();
  }, [selectedTarget]);

  useEffect(() => {
    if (!file) return;
    if (!commitTouched) setCommitMessage(generateCommitMessage(file.payload));
    if (!prBodyTouched) setPrBody(generatePrBody(file.payload));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [file?.payload]);

  if (targetsLoading) {
    return <p>Loading GitHub targets…</p>;
  }
  if (targetsError) {
    return (
      <div>
        <h1>Custom Fields</h1>
        <p style={{ color: "var(--danger)" }}>Could not load GitHub targets: {targetsError}</p>
        <button onClick={() => void loadTargets()}>Retry</button>
      </div>
    );
  }
  if (targets.length === 0) {
    return (
      <div>
        <h1>Custom Fields</h1>
        <p className="page-subtitle">Add a GitHub target first — the custom-fields template lives in that repo, in its own folder.</p>
      </div>
    );
  }
  if (!file) {
    return (
      <div>
        <h1>Custom Fields</h1>
        <div className="toolbar">
          <select value={selectedTarget} onChange={(e) => setSelectedTarget(e.target.value)} style={{ maxWidth: 280 }}>
            {targets.map((target) => (
              <option key={target.id} value={target.id}>{target.name} ({target.repo}@{target.branch})</option>
            ))}
          </select>
        </div>
        {fileLoading && <p>Loading custom-fields template…</p>}
        {fileError && (
          <div className="card" style={{ borderColor: "var(--danger)" }}>
            <p style={{ color: "var(--danger)" }}>Could not load the custom-fields template: {fileError}</p>
            <button onClick={() => void loadFile()}>Retry</button>
          </div>
        )}
      </div>
    );
  }

  const updateFields = (rows: Record<string, any>[]) => {
    setFile({ ...file, payload: { ...file.payload, custom_fields: rows } });
    setDirty(true);
  };
  const updateChoiceSets = (rows: Record<string, any>[]) => {
    setFile({ ...file, payload: { ...file.payload, custom_field_choice_sets: rows } });
    setDirty(true);
  };

  const fields: Record<string, any>[] = file.payload.custom_fields ?? [];
  const choiceSets: Record<string, any>[] = file.payload.custom_field_choice_sets ?? [];
  const choiceSetNames = choiceSets.map((c) => c.name);

  const saveFieldForm = (value: Record<string, any>) => {
    const next = [...fields];
    if (fieldFormOpen?.index == null) next.push(value); else next[fieldFormOpen.index] = value;
    updateFields(next);
    setFieldFormOpen(null);
  };
  const deleteField = (idx: number) => {
    if (!confirm(`Delete custom field "${fields[idx].name}"?`)) return;
    updateFields(fields.filter((_, i) => i !== idx));
  };

  const saveChoiceSetForm = (value: Record<string, any>) => {
    const next = [...choiceSets];
    if (choiceSetFormOpen?.index == null) next.push(value); else next[choiceSetFormOpen.index] = value;
    updateChoiceSets(next);
    setChoiceSetFormOpen(null);
  };
  const deleteChoiceSet = (idx: number) => {
    if (!confirm(`Delete choice set "${choiceSets[idx].name}"?`)) return;
    updateChoiceSets(choiceSets.filter((_, i) => i !== idx));
  };

  const handleSave = async () => {
    setSaving(true);
    setSaveError(null);
    try {
      const result = await customFieldsApi.save(selectedTarget, {
        payload: file.payload, sha: file.sha ?? undefined, commit_message: commitMessage, pr_body: prBody,
      });
      setLastResult(result);
      setDirty(false);
      loadFile();
    } catch (err: any) {
      setSaveError(err.message ?? "Save failed.");
    } finally {
      setSaving(false);
    }
  };

  const handleScanImport = async () => {
    if (!importInstance) return;
    setScanning(true);
    setScanError(null);
    setCandidates(null);
    setSelectedCandidates(new Set());
    setImportResult(null);
    try {
      const result = await customFieldsApi.scanImport(selectedTarget, importInstance);
      setCandidates(result.candidates);
    } catch (err: any) {
      setScanError(err.message ?? "Scan failed.");
    } finally {
      setScanning(false);
    }
  };

  const candidateKey = (c: ImportCandidate) => `${c.kind}:${c.name}`;
  const toggleCandidate = (key: string) => {
    setSelectedCandidates((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key); else next.add(key);
      return next;
    });
  };

  const handleImportSelected = async () => {
    if (!candidates) return;
    const selected = candidates.filter((c) => selectedCandidates.has(candidateKey(c)))
      .map((c) => ({ kind: c.kind, name: c.name }));
    if (selected.length === 0) return;
    setImporting(true);
    setImportError(null);
    try {
      const result = await customFieldsApi.importSelected(selectedTarget, { instance_id: importInstance, selected });
      setImportResult(result);
      setCandidates(null);
      setSelectedCandidates(new Set());
      loadFile();
    } catch (err: any) {
      setImportError(err.message ?? "Import failed.");
    } finally {
      setImporting(false);
    }
  };

  const handlePreviewPush = async () => {
    setPreviewingPush(true);
    setPushResults([]);
    try {
      setPushPreviews(await customFieldsApi.previewPush(selectedTarget, selectedInstances, [], overwrite, backupEnabled));
    } finally {
      setPreviewingPush(false);
    }
  };

  const downloadBackup = (preview: InstanceScopePreview) => {
    if (!preview.backup) return;
    const blob = new Blob([JSON.stringify(preview.backup, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `netbox-custom-fields-${preview.instance_name}-${new Date().toISOString().replace(/[:.]/g, "-")}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePush = async () => {
    if (!pushPreviews) return;
    const confirmations: Record<string, Record<string, any>> = {};
    for (const preview of pushPreviews) {
      if (!preview.reductions.length || !preview.confirmation_token) continue;
      if (backupEnabled) downloadBackup(preview);
      confirmations[preview.instance_id] = {
        token: preview.confirmation_token,
        typed_field_names: scopeConfirmations[preview.instance_id] ?? "",
        backup_acknowledged: backupEnabled && !!preview.backup,
        backup_opt_out_confirmation: backupOptOutConfirmations[preview.instance_id] ?? null,
      };
    }
    const results = await customFieldsApi.push(selectedTarget, selectedInstances, [], overwrite, confirmations);
    setPushResults(results);
    setPushPreviews(null);
  };

  const handleRestore = async (dryRun: boolean) => {
    if (!restoreInstance || !restoreBackup) return;
    setRestoreResult(await customFieldsApi.restore(selectedTarget, restoreInstance, restoreBackup, dryRun));
  };

  const handleDiff = async () => {
    if (selectedInstances.length === 0) return;
    setDiffing(true);
    try {
      const results = await customFieldsApi.diff(selectedTarget, selectedInstances, []);
      setDiffResults(results);
    } finally {
      setDiffing(false);
    }
  };

  const allTags = Array.from(new Set(instances.flatMap((i) => i.tags))).sort();
  const selectByTag = (tag: string) => {
    const matching = instances.filter((i) => i.tags.includes(tag)).map((i) => i.id);
    setSelectedInstances((prev) => Array.from(new Set([...prev, ...matching])));
  };

  const yamlPreview = yaml.dump(file.payload, { sortKeys: false });

  return (
    <div>
      <h1>Custom Fields Template</h1>
      <div className="toolbar">
        <select value={selectedTarget} onChange={(e) => setSelectedTarget(e.target.value)} style={{ maxWidth: 280 }}>
          {targets.map((t) => <option key={t.id} value={t.id}>{t.name} ({t.repo}@{t.branch})</option>)}
        </select>
      </div>
      <p className="page-subtitle mono">
        {file.exists
          ? file.path
          : <span className="pill" style={{ color: "var(--warning)" }}>template doesn't exist in this repo yet — save to create it</span>}
      </p>
      {file.open_pr && (
        <div className="card" style={{ borderColor: "var(--warning)" }}>
          <p style={{ fontSize: 13, margin: 0 }}>
            This template already has an open pull request —{" "}
            <a href={file.open_pr.url} target="_blank" rel="noreferrer" style={{ color: "var(--accent)" }}>PR #{file.open_pr.number}</a>.
            Saving again adds another commit to that same PR.
          </p>
        </div>
      )}

      <div className="editor-layout">
        <div>
          <div className="tabs">
            <button className={activeTab === "fields" ? "active" : ""} onClick={() => setActiveTab("fields")}>
              Custom Fields ({(file.payload.custom_fields ?? []).length})
            </button>
            <button className={activeTab === "choice-sets" ? "active" : ""} onClick={() => setActiveTab("choice-sets")}>
              Choice Sets ({(file.payload.custom_field_choice_sets ?? []).length})
            </button>
            <button className={activeTab === "publish" ? "active" : ""} onClick={() => setActiveTab("publish")}>
              Import / Push / Drift
            </button>
          </div>

          {activeTab === "fields" && (
            <div className="card">
              <div className="toolbar">
                <button className="primary" onClick={() => setFieldFormOpen({ index: null })}>+ Add Custom Field</button>
              </div>
              <table>
                <thead><tr><th>Name</th><th>Label</th><th>Type</th><th>Model(s)</th><th>Required</th><th></th></tr></thead>
                <tbody>
                  {fields.map((f, idx) => (
                    <tr key={f.name || idx}>
                      <td className="mono">{f.name}</td>
                      <td>{f.label || "—"}</td>
                      <td>{f.type}</td>
                      <td>{(f.object_types ?? []).length} model(s)</td>
                      <td>{f.required ? "Yes" : "No"}</td>
                      <td className="list-table-actions">
                        <button onClick={() => setFieldFormOpen({ index: idx })} style={{ padding: "2px 8px" }}>Edit</button>{" "}
                        <button className="danger" onClick={() => deleteField(idx)} style={{ padding: "2px 8px" }}>Delete</button>
                      </td>
                    </tr>
                  ))}
                  {fields.length === 0 && <tr><td colSpan={6} style={{ color: "var(--muted)" }}>No custom fields yet.</td></tr>}
                </tbody>
              </table>
            </div>
          )}
          {activeTab === "choice-sets" && (
            <div className="card">
              <div className="toolbar">
                <button className="primary" onClick={() => setChoiceSetFormOpen({ index: null })}>+ Add Choice Set</button>
              </div>
              <table>
                <thead><tr><th>Name</th><th>Description</th><th>Base choices</th><th>Extra choices</th><th></th></tr></thead>
                <tbody>
                  {choiceSets.map((c, idx) => (
                    <tr key={c.name || idx}>
                      <td className="mono">{c.name}</td>
                      <td>{c.description || "—"}</td>
                      <td>{c.base_choices || "—"}</td>
                      <td>{(c.extra_choices ?? []).length}</td>
                      <td className="list-table-actions">
                        <button onClick={() => setChoiceSetFormOpen({ index: idx })} style={{ padding: "2px 8px" }}>Edit</button>{" "}
                        <button className="danger" onClick={() => deleteChoiceSet(idx)} style={{ padding: "2px 8px" }}>Delete</button>
                      </td>
                    </tr>
                  ))}
                  {choiceSets.length === 0 && <tr><td colSpan={5} style={{ color: "var(--muted)" }}>No choice sets yet.</td></tr>}
                </tbody>
              </table>
            </div>
          )}

          {fieldFormOpen && (
            <CustomFieldForm
              initial={fieldFormOpen.index != null ? fields[fieldFormOpen.index] : null}
              existingNames={fields.filter((_, i) => i !== fieldFormOpen.index).map((f) => f.name)}
              choiceSetNames={choiceSetNames}
              onSave={saveFieldForm}
              onCancel={() => setFieldFormOpen(null)}
            />
          )}
          {choiceSetFormOpen && (
            <ChoiceSetForm
              initial={choiceSetFormOpen.index != null ? choiceSets[choiceSetFormOpen.index] : null}
              existingNames={choiceSets.filter((_, i) => i !== choiceSetFormOpen.index).map((c) => c.name)}
              onSave={saveChoiceSetForm}
              onCancel={() => setChoiceSetFormOpen(null)}
            />
          )}

          {activeTab === "publish" && (
            <div>
              <div className="card">
                <h2>Import from a NetBox instance</h2>
                <p style={{ color: "var(--muted)", fontSize: 13, marginTop: -6 }}>
                  Scans the instance and shows only what's missing from the template or differs from it — pick
                  which ones to bring in. Nothing changes until you import your selection, and that's a PR too.
                </p>
                <div className="form-row">
                  <select value={importInstance} onChange={(e) => { setImportInstance(e.target.value); setCandidates(null); }}>
                    <option value="">— select instance —</option>
                    {instances.map((i) => <option key={i.id} value={i.id}>{i.name}</option>)}
                  </select>
                </div>
                <button className="primary" disabled={!importInstance || scanning} onClick={handleScanImport}>
                  {scanning ? "Scanning…" : "Scan for differences"}
                </button>
                {scanError && <p style={{ color: "var(--danger)", fontSize: 13 }}>{scanError}</p>}

                {candidates && candidates.length === 0 && (
                  <p style={{ color: "var(--success)", fontSize: 13, marginTop: 10 }}>
                    Nothing to import — the template already covers everything on this instance.
                  </p>
                )}

                {candidates && candidates.length > 0 && (
                  <div style={{ marginTop: 10 }}>
                    <table>
                      <thead><tr><th></th><th>Kind</th><th>Name</th><th>Status</th><th>What differs</th></tr></thead>
                      <tbody>
                        {candidates.map((c) => {
                          const key = candidateKey(c);
                          return (
                            <tr key={key}>
                              <td><input type="checkbox" style={{ width: "auto" }} checked={selectedCandidates.has(key)} onChange={() => toggleCandidate(key)} /></td>
                              <td>{c.kind === "custom_field" ? "Field" : "Choice set"}</td>
                              <td className="mono">{c.name}</td>
                              <td>{c.status === "missing"
                                ? <span className="pill" style={{ color: "var(--danger)" }}>missing from template</span>
                                : <span className="pill" style={{ color: "var(--warning)" }}>differs</span>}</td>
                              <td style={{ fontSize: 12 }}>
                                {c.status === "changed" && c.field_changes.map((fc) => (
                                  <div key={fc.field} className="mono">{fc.field}: {JSON.stringify(fc.source)} → {JSON.stringify(fc.existing)}</div>
                                ))}
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                    <div className="toolbar" style={{ marginTop: 10 }}>
                      <button onClick={() => setSelectedCandidates(new Set(candidates.map(candidateKey)))}>Select all</button>
                      <button onClick={() => setSelectedCandidates(new Set())}>Clear</button>
                      <button className="primary" disabled={selectedCandidates.size === 0 || importing} onClick={handleImportSelected}>
                        {importing ? "Importing…" : `Import ${selectedCandidates.size || ""} selected & open PR`}
                      </button>
                    </div>
                  </div>
                )}
                {importError && <p style={{ color: "var(--danger)", fontSize: 13 }}>{importError}</p>}
                {importResult && (
                  <p style={{ fontSize: 13, marginTop: 8 }}>
                    <span className="status-dot status-ok" />
                    Imported — <a href={importResult.pr_url} target="_blank" rel="noreferrer" style={{ color: "var(--accent)" }}>PR #{importResult.pr_number}</a>
                  </p>
                )}
              </div>

              <div className="card">
                <h2>Push to NetBox instance(s)</h2>
                <p style={{ color: "var(--muted)", fontSize: 13, marginTop: -6 }}>
                  Pushes the template's current merged (base-branch) state. Missing fields/choice sets are created;
                  existing ones are only updated if "Overwrite" is checked.
                </p>
                {allTags.length > 0 && (
                  <div style={{ marginBottom: 10 }}>
                    <span style={{ fontSize: 12, color: "var(--muted)", marginRight: 8 }}>Select by tag:</span>
                    {allTags.map((tag) => (
                      <button key={tag} onClick={() => selectByTag(tag)} style={{ marginRight: 6, padding: "3px 10px", fontSize: 12 }}>
                        {tag} ({instances.filter((i) => i.tags.includes(tag)).length})
                      </button>
                    ))}
                    <button onClick={() => setSelectedInstances(instances.map((i) => i.id))} style={{ padding: "3px 10px", fontSize: 12 }}>all</button>
                    <button onClick={() => setSelectedInstances([])} style={{ padding: "3px 10px", fontSize: 12 }}>clear</button>
                  </div>
                )}
                {instances.map((inst) => (
                  <label key={inst.id} style={{ display: "block", marginBottom: 6 }}>
                    <input
                      type="checkbox" style={{ width: "auto", marginRight: 6 }}
                      checked={selectedInstances.includes(inst.id)}
                      onChange={(e) => { setPushPreviews(null); setSelectedInstances((prev) =>
                        e.target.checked ? [...prev, inst.id] : prev.filter((x) => x !== inst.id)); }}
                    />
                    {inst.name}
                    {inst.requires_approved_pr && <span className="pill" style={{ marginLeft: 6 }}>🔒 needs approved PR</span>}
                  </label>
                ))}
                <label style={{ display: "block", margin: "10px 0" }}>
                  <input type="checkbox" style={{ width: "auto", marginRight: 6 }} checked={overwrite}
                    onChange={(e) => { setOverwrite(e.target.checked); setPushPreviews(null); }} />
                  Overwrite existing fields/choice sets
                </label>
                {overwrite && (
                  <label style={{ display: "block", margin: "10px 0" }}>
                    <input type="checkbox" style={{ width: "auto", marginRight: 6 }} checked={backupEnabled}
                      onChange={(e) => { setBackupEnabled(e.target.checked); setPushPreviews(null); }} />
                    Download a JSON backup before any custom-field scope reduction (recommended)
                  </label>
                )}
                <div className="toolbar">
                  <button disabled={selectedInstances.length === 0 || diffing} onClick={handleDiff}>
                    {diffing ? "Checking…" : "Check drift"}
                  </button>
                  <button className="primary" disabled={selectedInstances.length === 0 || previewingPush} onClick={handlePreviewPush}>
                    {previewingPush ? "Inspecting values…" : `Review push to ${selectedInstances.length || ""} instance(s)`}
                  </button>
                </div>

                {pushPreviews && pushPreviews.map((preview) => (
                  <div key={preview.instance_id} className="card" style={{ borderColor: preview.reductions.length ? "var(--danger)" : "var(--success)" }}>
                    <h3>{preview.instance_name}</h3>
                    {preview.error ? <p style={{ color: "var(--danger)" }}>{preview.error}</p> : preview.reductions.length === 0 ? (
                      <p style={{ color: "var(--success)" }}>No custom-field scope reduction detected.</p>
                    ) : (
                      <>
                        <p style={{ color: "var(--danger)", fontWeight: 600 }}>
                          Removing these object types will permanently strip custom-field values in NetBox.
                        </p>
                        {preview.reductions.map((reduction) => (
                          <div key={reduction.field_name} style={{ marginBottom: 12 }}>
                            <strong className="mono">{reduction.field_name}</strong>
                            {reduction.object_types.map((row) => (
                              <div key={row.object_type} style={{ fontSize: 13, marginTop: 4 }}>
                                <span className="mono">{row.object_type}</span>: {row.meaningful_count} meaningful value(s)
                                across {row.raw_count} record(s) ({row.counting_method === "cf_empty_filter" ? "server-side filter" : "client-side count"})
                                {row.sample.length > 0 && (
                                  <ul>{row.sample.map((sample) => <li key={String(sample.id)}>{sample.display} (#{sample.id}): {JSON.stringify(sample.value)}</li>)}</ul>
                                )}
                              </div>
                            ))}
                          </div>
                        ))}
                        <div className="form-row">
                          <label>Type <span className="mono">{preview.confirmation_text}</span> to confirm</label>
                          <input className="mono" value={scopeConfirmations[preview.instance_id] ?? ""}
                            onChange={(e) => setScopeConfirmations((old) => ({ ...old, [preview.instance_id]: e.target.value }))} />
                        </div>
                        {backupEnabled && preview.backup && (
                          <button onClick={() => downloadBackup(preview)}>Download backup now</button>
                        )}
                        {!backupEnabled && (
                          <div className="form-row">
                            <label>Backup opt-out: type <span className="mono">NO BACKUP {preview.confirmation_text}</span></label>
                            <input className="mono" value={backupOptOutConfirmations[preview.instance_id] ?? ""}
                              onChange={(e) => setBackupOptOutConfirmations((old) => ({ ...old, [preview.instance_id]: e.target.value }))} />
                          </div>
                        )}
                      </>
                    )}
                  </div>
                ))}
                {pushPreviews && (
                  <button className="primary" disabled={pushPreviews.some((p) => !!p.error)} onClick={handlePush}>
                    Apply reviewed push
                  </button>
                )}

                {diffResults && diffResults.map((r) => (
                  <div key={r.instance_id} className="card" style={{ background: "var(--panel-raised)" }}>
                    <p style={{ fontWeight: 600, marginBottom: 6 }}>{r.instance_name}</p>
                    {r.error ? (
                      <p style={{ color: "var(--danger)", fontSize: 13 }}>Could not check: {r.error}</p>
                    ) : r.diff ? (
                      <CustomFieldsDiffView diff={r.diff} />
                    ) : null}
                  </div>
                ))}
                {pushResults.map((r, i) => (
                  <div key={i} style={{ fontSize: 13 }}>
                  <p>
                    <span className={`status-dot ${r.status === "success" ? "status-ok" : "status-error"}`} />
                    {r.target}: {r.detail}
                  </p>
                  {r.warnings?.map((warning) => <p key={warning} style={{ color: "var(--warning)" }}>Warning: {warning}</p>)}
                  </div>
                ))}
              </div>

              <div className="card">
                <h2>Restore custom-field values</h2>
                <p style={{ color: "var(--muted)", fontSize: 13 }}>
                  Upload a backup created during scope-reduction review. Dry-run verifies the hash, instance, records, and values without changing NetBox.
                </p>
                <div className="form-row">
                  <label>Instance</label>
                  <select value={restoreInstance} onChange={(e) => setRestoreInstance(e.target.value)}>
                    <option value="">— select instance —</option>
                    {instances.map((i) => <option key={i.id} value={i.id}>{i.name}</option>)}
                  </select>
                </div>
                <div className="form-row">
                  <label>Backup JSON</label>
                  <input type="file" accept="application/json,.json" onChange={async (e) => {
                    const selected = e.target.files?.[0];
                    try {
                      setRestoreBackup(selected ? JSON.parse(await selected.text()) : null);
                      setRestoreResult(null);
                    } catch {
                      setRestoreBackup(null);
                      setRestoreResult({ error: "The selected file is not valid JSON." });
                    }
                  }} />
                </div>
                <div className="toolbar">
                  <button disabled={!restoreInstance || !restoreBackup} onClick={() => handleRestore(true)}>Dry run</button>
                  <button className="danger" disabled={!restoreInstance || !restoreBackup}
                    onClick={() => confirm("Re-add object types and restore these custom-field values?") && handleRestore(false)}>Apply restore</button>
                </div>
                {restoreResult && <pre className="yaml-preview mono">{JSON.stringify(restoreResult, null, 2)}</pre>}
              </div>
            </div>
          )}

          <div className="card" style={{ marginTop: 8 }}>
            <h2>Commit</h2>
            <p style={{ color: "var(--muted)", fontSize: 13, marginTop: -6 }}>
              Direct commits are disabled — saving always opens (or updates) a pull request for review.
            </p>
            <div className="form-row">
              <label>PR title / commit message</label>
              <input value={commitMessage} onChange={(e) => { setCommitMessage(e.target.value); setCommitTouched(true); }} />
            </div>
            <div className="form-row">
              <label>PR description</label>
              <textarea rows={4} className="mono" value={prBody} onChange={(e) => { setPrBody(e.target.value); setPrBodyTouched(true); }} />
            </div>
            <button className="primary" disabled={!dirty || saving} onClick={handleSave}>
              {saving ? "Opening PR…" : dirty ? "Save (open pull request)" : "Saved"}
            </button>
            {saveError && <p style={{ color: "var(--danger)", fontSize: 13 }}>{saveError}</p>}
            {lastResult && !dirty && (
              <p style={{ fontSize: 13 }}>
                <span className="status-dot status-ok" />
                Saved to <a href={lastResult.pr_url} target="_blank" rel="noreferrer" style={{ color: "var(--accent)" }}>PR #{lastResult.pr_number}</a>
              </p>
            )}
          </div>
        </div>

        <div>
          <h2>YAML preview</h2>
          <pre className="yaml-preview mono">{yamlPreview}</pre>
        </div>
      </div>
    </div>
  );
}
