import { useEffect, useState } from "react";
import { useLocation, useNavigate, useParams, useSearchParams } from "react-router-dom";
import * as yaml from "js-yaml";
import { deviceTypesApi, instancesApi, NetboxInstance, InstanceDiffResult } from "../api/client";
import ComponentGrid, { FieldDef } from "../components/ComponentGrid";
import DeviceTypeCustomFields from "../components/DeviceTypeCustomFields";
import DiffView from "../components/DiffView";
import ImagePreviewModal, { ActiveImagePreview } from "../components/ImagePreviewModal";

const COMPONENT_SUMMARY_LABELS: [string, string][] = [
  ["interfaces", "interface(s)"],
  ["console-ports", "console port(s)"],
  ["console-server-ports", "console server port(s)"],
  ["power-ports", "power port(s)"],
  ["power-outlets", "power outlet(s)"],
  ["rear-ports", "rear port(s)"],
  ["front-ports", "front port(s)"],
  ["device-bays", "device bay(s)"],
  ["module-bays", "module bay(s)"],
];

function generateCommitMessage(payload: Record<string, any>, isNew: boolean): string {
  const verb = isNew ? "Add" : "Update";
  return `${verb} device-type ${payload.manufacturer ?? ""} ${payload.model ?? ""}`.trim();
}

function generatePrBody(payload: Record<string, any>, isNew: boolean): string {
  const header = isNew
    ? `Adds a new device type: **${payload.manufacturer ?? "?"} ${payload.model ?? "?"}**`
    : `Updates device type: **${payload.manufacturer ?? "?"} ${payload.model ?? "?"}**`;
  const lines = COMPONENT_SUMMARY_LABELS
    .map(([key, label]) => ({ count: (payload[key] ?? []).length, label }))
    .filter((x) => x.count > 0)
    .map((x) => `- ${x.count} ${x.label}`);
  const customFieldCount = Object.keys(payload.custom_fields ?? {}).length;
  if (customFieldCount > 0) lines.push(`- ${customFieldCount} custom field value(s)`);
  const body = lines.length ? lines.join("\n") : "- No components defined yet";
  return `${header}\n\n${body}\n\n_Generated by NetBox Manager._`;
}

export function toNetboxImportYaml(payload: Record<string, any>): Record<string, any> {
  const native = { ...payload };
  const customFields = native.custom_fields ?? {};
  delete native.custom_fields;
  Object.entries(customFields).forEach(([name, value]) => { native[`cf_${name}`] = value; });
  return native;
}

export function updateDeviceTypeField(
  payload: Record<string, any>, key: string, value: unknown,
): Record<string, any> {
  return { ...payload, [key]: value };
}

const INTERFACE_TYPES = [
  "virtual", "lag", "100base-tx", "1000base-t", "2.5gbase-t", "5gbase-t", "10gbase-t",
  "10gbase-x-sfpp", "25gbase-x-sfp28", "40gbase-x-qsfpp", "100gbase-x-qsfp28", "other",
];

const TABS: { key: string; label: string; namePattern?: boolean; fields: FieldDef[] }[] = [
  {
    key: "interfaces", label: "Interfaces", namePattern: true,
    fields: [
      { key: "name", label: "Name", width: "30%" },
      { key: "type", label: "Type", type: "select", options: INTERFACE_TYPES, width: "25%" },
      { key: "mgmt_only", label: "Mgmt only", type: "checkbox", width: "10%" },
      { key: "label", label: "Label" },
    ],
  },
  {
    key: "console-ports", label: "Console Ports", namePattern: true,
    fields: [
      { key: "name", label: "Name", width: "40%" },
      { key: "type", label: "Type", type: "select", options: ["rj-45", "usb-a", "usb-b", "usb-micro-b", "other"] },
    ],
  },
  {
    key: "console-server-ports", label: "Console Server Ports", namePattern: true,
    fields: [
      { key: "name", label: "Name", width: "40%" },
      { key: "type", label: "Type", type: "select", options: ["rj-45", "usb-a", "other"] },
    ],
  },
  {
    key: "power-ports", label: "Power Ports", namePattern: true,
    fields: [
      { key: "name", label: "Name", width: "30%" },
      { key: "type", label: "Type", type: "select", options: ["iec-60320-c14", "iec-60320-c20", "nema-5-15p", "other"] },
      { key: "maximum_draw", label: "Max draw (W)", type: "number" },
      { key: "allocated_draw", label: "Alloc draw (W)", type: "number" },
    ],
  },
  {
    key: "power-outlets", label: "Power Outlets", namePattern: true,
    fields: [
      { key: "name", label: "Name", width: "40%" },
      { key: "type", label: "Type", type: "select", options: ["iec-60320-c13", "iec-60320-c19", "nema-5-15r", "other"] },
      { key: "power_port", label: "Power port" },
    ],
  },
  {
    key: "rear-ports", label: "Rear Ports", namePattern: true,
    fields: [
      { key: "name", label: "Name", width: "40%" },
      { key: "type", label: "Type", type: "select", options: ["8p8c", "lc", "sc", "other"] },
      { key: "positions", label: "Positions", type: "number" },
    ],
  },
  {
    key: "front-ports", label: "Front Ports", namePattern: true,
    fields: [
      { key: "name", label: "Name", width: "30%" },
      { key: "type", label: "Type", type: "select", options: ["8p8c", "lc", "sc", "other"] },
      { key: "rear_port", label: "Rear port" },
      { key: "rear_port_position", label: "Rear pos", type: "number" },
    ],
  },
  {
    key: "device-bays", label: "Device Bays", namePattern: true,
    fields: [{ key: "name", label: "Name", width: "60%" }, { key: "label", label: "Label" }],
  },
  {
    key: "module-bays", label: "Module Bays", namePattern: true,
    fields: [{ key: "name", label: "Name", width: "40%" }, { key: "position", label: "Position" }],
  },
];

export default function DeviceTypeEditorPage() {
  const { targetId } = useParams<{ targetId: string }>();
  const [searchParams] = useSearchParams();
  const location = useLocation();
  const navigate = useNavigate();
  const path = searchParams.get("path") ?? "";
  const draftPayload = (location.state as { draftPayload?: Record<string, any> } | null)?.draftPayload;
  const isNew = !path; // no path yet means this hasn't been committed to GitHub at all

  const [payload, setPayload] = useState<Record<string, any> | null>(isNew ? (draftPayload ?? null) : null);
  const [sha, setSha] = useState<string | undefined>(undefined);
  const [existingPr, setExistingPr] = useState<{ number: number; url: string } | null>(null);
  const [imageStatus, setImageStatus] = useState<Record<string, "present" | "missing">>({});
  const [activeTab, setActiveTab] = useState("basic");
  const [saving, setSaving] = useState(false);
  const [dirty, setDirty] = useState(isNew); // a fresh/imported draft is "dirty" until its first commit
  const [commitMessage, setCommitMessage] = useState("");
  const [commitMessageTouched, setCommitMessageTouched] = useState(false);
  const [prBody, setPrBody] = useState("");
  const [prBodyTouched, setPrBodyTouched] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [lastResult, setLastResult] = useState<{ pr_number: number; pr_url: string } | null>(null);

  const [instances, setInstances] = useState<NetboxInstance[]>([]);
  const [selectedInstances, setSelectedInstances] = useState<string[]>([]);
  const [overwrite, setOverwrite] = useState(false);
  const [pushResults, setPushResults] = useState<{ target: string; status: string; detail?: string }[]>([]);
  const [diffResults, setDiffResults] = useState<InstanceDiffResult[] | null>(null);
  const [diffing, setDiffing] = useState(false);
  const [activeImage, setActiveImage] = useState<ActiveImagePreview>(null);
  const [imageError, setImageError] = useState<string | null>(null);

  useEffect(() => {
    if (!targetId || isNew) return; // new drafts already have their payload from router state
    deviceTypesApi.get(targetId, path).then((f) => {
      setPayload(f.payload);
      setSha(f.sha);
      setExistingPr(f.open_pr ?? null);
      setImageStatus(f.image_status ?? {});
    });
  }, [targetId, path, isNew]);

  useEffect(() => {
    instancesApi.list().then(setInstances);
  }, []);

  // Keep the commit message and PR description prefilled with a generated
  // summary until the user edits them by hand; once touched, stop overwriting.
  useEffect(() => {
    if (!payload) return;
    if (!commitMessageTouched) setCommitMessage(generateCommitMessage(payload, isNew));
    if (!prBodyTouched) setPrBody(generatePrBody(payload, isNew));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [payload, isNew]);

  if (!payload) return <p>{isNew ? "No draft data — go back and start a new device type." : "Loading from GitHub…"}</p>;

  const updateBasic = (key: string, value: any) => {
    setPayload(updateDeviceTypeField(payload, key, value)); setDirty(true);
  };
  const updateComponent = (key: string, rows: Record<string, any>[]) => { setPayload({ ...payload, [key]: rows }); setDirty(true); };

  const handleSave = async () => {
    if (!targetId) return;
    setSaving(true);
    setSaveError(null);
    try {
      if (isNew) {
        const result = await deviceTypesApi.create(targetId, {
          manufacturer: payload.manufacturer,
          model: payload.model,
          slug: payload.slug,
          payload,
          commit_message: commitMessage,
          pr_body: prBody,
        });
        setSha(result.sha);
        setDirty(false);
        setLastResult(result);
        // Swap the URL to the now-persisted file so a refresh/reload re-fetches from GitHub
        // instead of relying on router state, which doesn't survive a reload.
        navigate(`/device-types/${targetId}/edit?path=${encodeURIComponent(result.path)}`, { replace: true });
      } else {
        const result = await deviceTypesApi.save(targetId, path, {
          payload,
          sha,
          commit_message: commitMessage,
          pr_body: prBody,
        });
        setSha(result.sha);
        setDirty(false);
        setLastResult(result);
      }
    } catch (err: any) {
      setSaveError(err.message ?? "Save failed.");
    } finally {
      setSaving(false);
    }
  };

  const handlePushNetbox = async () => {
    if (!targetId) return;
    const results = await deviceTypesApi.pushToNetbox(targetId, path, selectedInstances, overwrite);
    setPushResults(results);
  };

  const handlePreviewDiff = async () => {
    if (!targetId || selectedInstances.length === 0) return;
    setDiffing(true);
    try {
      const results = await deviceTypesApi.diffWithNetbox(targetId, path, selectedInstances);
      setDiffResults(results);
    } finally {
      setDiffing(false);
    }
  };

  const previewImage = async (side: "front" | "rear") => {
    if (!targetId || isNew) return; setActiveImage("loading"); setImageError(null);
    try { setActiveImage({ ...(await deviceTypesApi.imagePreview(targetId, path, side)), title: `${payload.manufacturer} ${payload.model} — ${side}` }); }
    catch (error: any) { setActiveImage("error"); setImageError(error.message ?? "Image preview failed."); }
  };
  const uploadImage = async (side: "front" | "rear", file?: File) => {
    if (!targetId || isNew || !file) return; setImageError(null);
    const content_base64 = await new Promise<string>((resolve, reject) => {
      const reader = new FileReader(); reader.onerror = () => reject(reader.error); reader.onload = () => resolve(String(reader.result).split(",", 2)[1]); reader.readAsDataURL(file);
    });
    try {
      await deviceTypesApi.saveImage(targetId, path, { side, filename: file.name, content_type: file.type, content_base64 });
      const refreshed = await deviceTypesApi.get(targetId, path); setPayload(refreshed.payload); setSha(refreshed.sha); setImageStatus(refreshed.image_status); setDirty(false);
    } catch (error: any) { setImageError(error.message ?? "Image upload failed."); }
  };
  const removeImage = async (side: "front" | "rear") => {
    if (!targetId || isNew) return; setImageError(null);
    try { await deviceTypesApi.removeImage(targetId, path, side); const refreshed = await deviceTypesApi.get(targetId, path); setPayload(refreshed.payload); setSha(refreshed.sha); setImageStatus(refreshed.image_status); setDirty(false); }
    catch (error: any) { setImageError(error.message ?? "Image removal failed."); }
  };

  const allTags = Array.from(new Set(instances.flatMap((i) => i.tags))).sort();
  const selectByTag = (tag: string) => {
    const matching = instances.filter((i) => i.tags.includes(tag)).map((i) => i.id);
    setSelectedInstances((prev) => Array.from(new Set([...prev, ...matching])));
  };

  const yamlPreview = yaml.dump(toNetboxImportYaml(payload), { sortKeys: false });

  return (
    <div>
      <h1>{payload.manufacturer} {payload.model}</h1>
      <p className="page-subtitle mono">
        {isNew ? <span className="pill" style={{ color: "var(--warning)" }}>not saved yet — save to open a pull request</span> : path}
      </p>

      <div className="editor-layout">
        <div>
          <div className="tabs">
            <button className={activeTab === "basic" ? "active" : ""} onClick={() => setActiveTab("basic")}>Basic Info</button>
            {TABS.map((t) => (
              <button key={t.key} className={activeTab === t.key ? "active" : ""} onClick={() => setActiveTab(t.key)}>
                {t.label} {payload[t.key]?.length ? `(${payload[t.key].length})` : ""}
              </button>
            ))}
            <button className={activeTab === "custom-fields" ? "active" : ""} onClick={() => setActiveTab("custom-fields")}>
              Custom Fields {Object.keys(payload.custom_fields ?? {}).length ? `(${Object.keys(payload.custom_fields).length})` : ""}
            </button>
            <button className={activeTab === "publish" ? "active" : ""} onClick={() => setActiveTab("publish")}>Push to NetBox</button>
          </div>

          {activeTab === "basic" && (
            <div className="card">
              <div className="form-row"><label>Manufacturer</label>
                <input value={payload.manufacturer ?? ""} onChange={(e) => updateBasic("manufacturer", e.target.value)} /></div>
              <div className="form-row"><label>Model</label>
                <input value={payload.model ?? ""} onChange={(e) => updateBasic("model", e.target.value)} /></div>
              <div className="form-row"><label>Slug</label>
                <input className="mono" value={payload.slug ?? ""} onChange={(e) => updateBasic("slug", e.target.value)} /></div>
              <div className="form-row"><label>Part number</label>
                <input value={payload.part_number ?? ""} onChange={(e) => updateBasic("part_number", e.target.value)} /></div>
              <div className="form-row"><label>U height</label>
                <input type="number" step="0.5" value={payload.u_height ?? 1} onChange={(e) => updateBasic("u_height", parseFloat(e.target.value))} /></div>
              <div className="form-row"><label>
                <input type="checkbox" style={{ width: "auto", marginRight: 6 }} checked={!!payload.is_full_depth}
                  onChange={(e) => updateBasic("is_full_depth", e.target.checked)} />
                Full depth</label></div>
              {(["front", "rear"] as const).map((side) => <div className="form-row" key={side}>
                <label>{side === "front" ? "Front" : "Rear"} elevation image</label>
                <div className="toolbar"><span className="pill" style={{ color: imageStatus[side] === "present" ? "var(--success)" : "var(--muted)" }}>{imageStatus[side] === "present" ? "present" : "not attached"}</span>
                  <label className={`button-link file-button${isNew ? " disabled" : ""}`}>{imageStatus[side] === "present" ? "Replace" : "Attach"}<input hidden disabled={isNew} type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => { uploadImage(side, e.target.files?.[0]); e.target.value = ""; }} /></label>
                  <button disabled={isNew || imageStatus[side] !== "present"} onClick={() => previewImage(side)}>Preview</button>
                  <button className="danger" disabled={isNew || imageStatus[side] !== "present"} onClick={() => removeImage(side)}>Remove</button>
                </div>{isNew && <div className="field-help">Save the device type before attaching images.</div>}
              </div>)}
              {imageError && <p style={{ color: "var(--danger)" }}>{imageError}</p>}
              <div className="form-row"><label>Subdevice role</label>
                <select value={payload.subdevice_role ?? ""} onChange={(e) => updateBasic("subdevice_role", e.target.value || null)}>
                  <option value="">— none —</option>
                  <option value="parent">parent</option>
                  <option value="child">child</option>
                </select></div>
              <div className="form-row"><label>Weight</label>
                <input type="number" value={payload.weight ?? ""} onChange={(e) => updateBasic("weight", parseFloat(e.target.value))} /></div>
              <div className="form-row"><label>Weight unit</label>
                <select value={payload.weight_unit ?? ""} onChange={(e) => updateBasic("weight_unit", e.target.value || null)}>
                  <option value="">—</option>
                  <option value="kg">kg</option><option value="g">g</option><option value="lb">lb</option><option value="oz">oz</option>
                </select></div>
              <div className="form-row"><label>Comments</label>
                <textarea rows={3} value={payload.comments ?? ""} onChange={(e) => updateBasic("comments", e.target.value)} /></div>
            </div>
          )}

          {TABS.filter((t) => t.key === activeTab).map((t) => (
            <div className="card" key={t.key}>
              <ComponentGrid
                rows={payload[t.key] ?? []}
                fields={t.fields}
                namePattern={t.namePattern}
                onChange={(rows) => updateComponent(t.key, rows)}
              />
            </div>
          ))}

          {activeTab === "custom-fields" && targetId && (
            <DeviceTypeCustomFields
              targetId={targetId}
              values={payload.custom_fields ?? {}}
              onChange={(v) => updateBasic("custom_fields", v)}
            />
          )}

          {activeTab === "publish" && isNew && (
            <div className="card">
              <h2>Push to NetBox instance(s)</h2>
              <p style={{ color: "var(--muted)" }}>Save this device type (opens a pull request) below before pushing it to NetBox.</p>
            </div>
          )}

          {activeTab === "publish" && !isNew && (
            <div className="card">
              <h2>Push to NetBox instance(s)</h2>
              <p style={{ color: "var(--muted)", fontSize: 13, marginTop: -6 }}>
                Pushes the version currently merged into the repo's base branch — not any pending, unmerged PR changes.
              </p>
              {instances.length === 0 && <p style={{ color: "var(--muted)" }}>No instances configured yet — add one under NetBox Instances.</p>}
              {allTags.length > 0 && (
                <div style={{ marginBottom: 10 }}>
                  <span style={{ fontSize: 12, color: "var(--muted)", marginRight: 8 }}>Select by tag:</span>
                  {allTags.map((tag) => (
                    <button key={tag} onClick={() => selectByTag(tag)} style={{ marginRight: 6, padding: "3px 10px", fontSize: 12 }}>
                      {tag} ({instances.filter((i) => i.tags.includes(tag)).length})
                    </button>
                  ))}
                  <button onClick={() => setSelectedInstances(instances.map((i) => i.id))} style={{ padding: "3px 10px", fontSize: 12 }}>
                    all ({instances.length})
                  </button>
                  <button onClick={() => setSelectedInstances([])} style={{ padding: "3px 10px", fontSize: 12 }}>clear</button>
                </div>
              )}
              {instances.map((inst) => (
                <label key={inst.id} style={{ display: "block", marginBottom: 6 }}>
                  <input
                    type="checkbox" style={{ width: "auto", marginRight: 6 }}
                    checked={selectedInstances.includes(inst.id)}
                    onChange={(e) => setSelectedInstances((prev) =>
                      e.target.checked ? [...prev, inst.id] : prev.filter((x) => x !== inst.id))}
                  />
                  {inst.name} <span className="mono" style={{ color: "var(--muted)" }}>{inst.base_url}</span>
                  {inst.requires_approved_pr && <span className="pill" style={{ marginLeft: 6 }}>🔒 needs approved PR</span>}
                  {inst.tags.map((t) => <span key={t} className="pill" style={{ marginLeft: 4 }}>{t}</span>)}
                </label>
              ))}
              <label style={{ display: "block", margin: "10px 0" }}>
                <input type="checkbox" style={{ width: "auto", marginRight: 6 }} checked={overwrite} onChange={(e) => setOverwrite(e.target.checked)} />
                Overwrite if the device type already exists
              </label>
              <div className="toolbar" style={{ marginBottom: 4 }}>
                <button disabled={selectedInstances.length === 0 || diffing} onClick={handlePreviewDiff}>
                  {diffing ? "Diffing…" : "Preview diff"}
                </button>
                <button className="primary" disabled={selectedInstances.length === 0} onClick={handlePushNetbox}>
                  Push to {selectedInstances.length || ""} instance(s)
                </button>
              </div>

              {diffResults && diffResults.map((r) => (
                <div key={r.instance_id} className="card" style={{ background: "var(--panel-raised)" }}>
                  <p style={{ fontWeight: 600, marginBottom: 6 }}>{r.instance_name}</p>
                  {r.error ? (
                    <p style={{ color: "var(--danger)", fontSize: 13 }}>Could not diff: {r.error}</p>
                  ) : r.diff ? (
                    <DiffView diff={r.diff} />
                  ) : null}
                </div>
              ))}

              {pushResults.map((r, i) => (
                <p key={i} style={{ fontSize: 13 }}>
                  <span className={`status-dot ${r.status === "success" ? "status-ok" : "status-error"}`} />
                  {r.target}: {r.detail}
                </p>
              ))}
            </div>
          )}

          {existingPr && (
            <div className="card" style={{ borderColor: "var(--warning)" }}>
              <p style={{ fontSize: 13, margin: 0 }}>
                This device type already has an open pull request —{" "}
                <a href={existingPr.url} target="_blank" rel="noreferrer" style={{ color: "var(--accent)" }}>
                  PR #{existingPr.number}
                </a>. Saving again adds another commit to that same PR.
              </p>
            </div>
          )}

          <div className="card" style={{ marginTop: 8 }}>
            <h2>Open pull request</h2>
            <p style={{ color: "var(--muted)", fontSize: 13, marginTop: -6 }}>
              Direct commits are disabled — saving always opens (or updates) a pull request for review.
            </p>
            <div className="form-row">
              <label>PR title / commit message</label>
              <input
                value={commitMessage}
                onChange={(e) => { setCommitMessage(e.target.value); setCommitMessageTouched(true); }}
              />
            </div>
            <div className="form-row">
              <label>PR description</label>
              <textarea
                rows={6}
                className="mono"
                value={prBody}
                onChange={(e) => { setPrBody(e.target.value); setPrBodyTouched(true); }}
              />
            </div>
            <button className="primary" disabled={!dirty || saving} onClick={handleSave}>
              {saving ? "Opening PR…" : dirty ? "Save (open pull request)" : "Saved"}
            </button>
            {saveError && <p style={{ color: "var(--danger)", fontSize: 13 }}>{saveError}</p>}
            {lastResult && !dirty && (
              <p style={{ fontSize: 13 }}>
                <span className="status-dot status-ok" />
                Saved to{" "}
                <a href={lastResult.pr_url} target="_blank" rel="noreferrer" style={{ color: "var(--accent)" }}>
                  PR #{lastResult.pr_number}
                </a>
              </p>
            )}
          </div>
        </div>

        <div>
          <h2>YAML preview</h2>
          <pre className="yaml-preview mono">{yamlPreview}</pre>
        </div>
      </div>
      <ImagePreviewModal image={activeImage} onClose={() => setActiveImage(null)} />
    </div>
  );
}
